### ISSUE TITLE
Model cannot detect correctly

### ISSUE THREAD

**Issue by nguyenpbui** [gakkiri/simple-centernet-pytorch#6]
Hi @gakkiri ,
I used your work to train on COCO format of VISDrone dataset but the result is quite bad. I attached the result image below.  Did you experience this case and if yes, how did you solve it?
Thank you
![image](https://user-images.githubusercontent.com/34409468/129829727-246f9ba2-8950-405c-9e26-b42a062762c6.png)

**Comment by gakkiri** [comment]
Sorry, I recommend experimenting with voc.py and strongly suggest visualizing the final heat map results, which should work if they perform as expected. And coco.py is currently not fully tested.

**Comment by mnbrshd** [comment]
Getting the same issue. I visualized the heatmaps and there's nothing there.
